/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectId = IDL.Text;
export const TemplateId = IDL.Text;
export const Template = IDL.Record({
  'id' : TemplateId,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'category' : IDL.Text,
  'previewImageUrl' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'avatarUrl' : IDL.Text,
});
export const ChatMessageId = IDL.Text;
export const ChatMessage = IDL.Record({
  'id' : ChatMessageId,
  'content' : IDL.Text,
  'role' : IDL.Text,
  'projectId' : ProjectId,
  'timestamp' : Timestamp,
});
export const ProjectStatus = IDL.Variant({
  'live' : IDL.Null,
  'building' : IDL.Null,
  'draft' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : ProjectId,
  'status' : ProjectStatus,
  'owner' : IDL.Principal,
  'previewUrl' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'prompt' : IDL.Text,
});
export const UserSettings = IDL.Record({
  'theme' : IDL.Text,
  'notificationsEnabled' : IDL.Bool,
  'plan' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ProjectId], []),
  'deleteProject' : IDL.Func([ProjectId], [], []),
  'getAllTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatHistory' : IDL.Func([ProjectId], [IDL.Vec(ChatMessage)], ['query']),
  'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
  'getTemplate' : IDL.Func([TemplateId], [IDL.Opt(Template)], ['query']),
  'getTemplatesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Template)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getUserSettings' : IDL.Func([], [IDL.Opt(UserSettings)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveUserSettings' : IDL.Func([UserSettings], [], []),
  'sendMessage' : IDL.Func(
      [ProjectId, IDL.Text, IDL.Text],
      [ChatMessageId],
      [],
    ),
  'updateProject' : IDL.Func([ProjectId, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateProjectStatus' : IDL.Func([ProjectId, ProjectStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectId = IDL.Text;
  const TemplateId = IDL.Text;
  const Template = IDL.Record({
    'id' : TemplateId,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'category' : IDL.Text,
    'previewImageUrl' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'avatarUrl' : IDL.Text,
  });
  const ChatMessageId = IDL.Text;
  const ChatMessage = IDL.Record({
    'id' : ChatMessageId,
    'content' : IDL.Text,
    'role' : IDL.Text,
    'projectId' : ProjectId,
    'timestamp' : Timestamp,
  });
  const ProjectStatus = IDL.Variant({
    'live' : IDL.Null,
    'building' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : ProjectId,
    'status' : ProjectStatus,
    'owner' : IDL.Principal,
    'previewUrl' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'prompt' : IDL.Text,
  });
  const UserSettings = IDL.Record({
    'theme' : IDL.Text,
    'notificationsEnabled' : IDL.Bool,
    'plan' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ProjectId], []),
    'deleteProject' : IDL.Func([ProjectId], [], []),
    'getAllTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatHistory' : IDL.Func([ProjectId], [IDL.Vec(ChatMessage)], ['query']),
    'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
    'getTemplate' : IDL.Func([TemplateId], [IDL.Opt(Template)], ['query']),
    'getTemplatesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Template)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getUserSettings' : IDL.Func([], [IDL.Opt(UserSettings)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveUserSettings' : IDL.Func([UserSettings], [], []),
    'sendMessage' : IDL.Func(
        [ProjectId, IDL.Text, IDL.Text],
        [ChatMessageId],
        [],
      ),
    'updateProject' : IDL.Func(
        [ProjectId, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateProjectStatus' : IDL.Func([ProjectId, ProjectStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };