/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : ChatMessageId,
  'content' : string,
  'role' : string,
  'projectId' : ProjectId,
  'timestamp' : Timestamp,
}
export type ChatMessageId = string;
export interface Project {
  'id' : ProjectId,
  'status' : ProjectStatus,
  'owner' : Principal,
  'previewUrl' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'prompt' : string,
}
export type ProjectId = string;
export type ProjectStatus = { 'live' : null } |
  { 'building' : null } |
  { 'draft' : null };
export interface Template {
  'id' : TemplateId,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'category' : string,
  'previewImageUrl' : string,
}
export type TemplateId = string;
export type Timestamp = bigint;
export interface UserProfile {
  'displayName' : string,
  'createdAt' : Timestamp,
  'avatarUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings {
  'theme' : string,
  'notificationsEnabled' : boolean,
  'plan' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<[string, string], undefined>,
  'createProject' : ActorMethod<[string, string, string], ProjectId>,
  'deleteProject' : ActorMethod<[ProjectId], undefined>,
  'getAllTemplates' : ActorMethod<[], Array<Template>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatHistory' : ActorMethod<[ProjectId], Array<ChatMessage>>,
  'getProject' : ActorMethod<[ProjectId], [] | [Project]>,
  'getTemplate' : ActorMethod<[TemplateId], [] | [Template]>,
  'getTemplatesByCategory' : ActorMethod<[string], Array<Template>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProjects' : ActorMethod<[], Array<Project>>,
  'getUserSettings' : ActorMethod<[], [] | [UserSettings]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveUserSettings' : ActorMethod<[UserSettings], undefined>,
  'sendMessage' : ActorMethod<[ProjectId, string, string], ChatMessageId>,
  'updateProject' : ActorMethod<[ProjectId, string, string, string], undefined>,
  'updateProjectStatus' : ActorMethod<[ProjectId, ProjectStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];